### PR TITLE
Seeding calls and stored procedures for insertions

### PR DESCRIPTION
**Pull request by Ahmed-anwar**

### CODE REVIEW

**Comment by HatemMorgan** [comment]
Very good job :+1.
I tested all the stored procedures and all the insertion scripts. Really great job, thank you.

My only comment is about int(11) in the SPs.

I searched what INT(11) means and I found that this length specifies how many characters to display when selecting data with the mysql command line client.

The meaning of INT(11) is that no matter what, you want the integer to be shown at most with 11 digits. So if you store an integer that's larger than 11 digits - it will only be displayed as if it had 11 digits, but its actual value will be stored. 

For example: Column INT(4), integer 1 would be displayed as 0001 ONLY.

Reference: https://stackoverflow.com/questions/5634104/what-is-the-size-of-column-of-int11-in-mysql-in-bytes

In the create tables script we use int directly without defining a length.

**Comment by Ahmed-anwar** [comment]
@HatemMorgan thank you for the review.

When we used phpMyAdmin service to test the CreateScript, the stored type of ids in the tables were int(11) that's the reason why we used it. Do you think we should modify it?

**Comment by HatemMorgan** [comment]
@Ahmed-anwar with the description I found, I think we don't need it because I think we will need the full id length to search for user profiles in NoSql database.

**Comment by Ahmed-anwar** [comment]
@HatemMorgan 
resolved.

**Comment by HatemMorgan** [comment]
Tested and reviewed.

**Pull request merged**
