### PR TITLE
jobListing schema and documentation done

### PR DESCRIPTION
**Pull request by loayelzobeidy**

### CODE REVIEW

**Comment by HatemMorgan** [comment]
I reviewed both job listing schema and documentation. Great work :+1: .

I think that `"similarJobs":[{},{},{}]` needs to be written as `"similarJobs":[{"id":Integer, `"name":String,"companies":[{}]}]`  and also specify company object ((attributes)) that will be in this array.

The same thing for **relatedConnections** 

Thank you

**Comment by loayelzobeidy** [comment]
@HatemMorgan  we will embbed instead of this empty JSON objects jobs lightweight this a different jobs object having just the attributes you mentioned.

**Comment by mostafa-abdullah** [comment]
@loayelzobeidy I like the lightweight objects idea. Please do it so that we can merge the pull request.

**Comment by HatemMorgan** [comment]
Sorry, I don't understand what do you mean by "jobs lightweight"

**Comment by mostafa-abdullah** [comment]
@HatemMorgan for example instead of embedding the complete user profile document inside relatedConnections, we include only the interesting information (e.g., full name, profile picture)

**Comment by HatemMorgan** [comment]
@mostafa-abdullah this was what I meant. I was recommending from my point of view that we should include them in the schema instead of leaving it as an empty object. 

For example: `"similarJobs":[
                                                {
                                                     "id":Integer, 
                                                     "name":String,
                                                     "companies":[
                                                                             {
                                                                                 "id": Integer,
                                                                                 "name": String
                                                                              }
                                                                         ]
                                                   }
                                            ]`

**Comment by mostafa-abdullah** [comment]
@HatemMorgan Yes exactly I agree.

**Pull request closed without merging**
